### ISSUE TITLE
Comment assignment becomes ambigous

### ISSUE THREAD

**Issue by jrosebr1** [Py-Image/comment-assignment#1]
I found a use case when the comment assignment becomes ambiguous. To replicate:

1. Reply to a comment
2. Edit the comment you just sumbitted by visiting the website, clicking on the blog post, scrolling down to a comment, and clicking "Edit"
3. Edit the comment and approve

Once the comment has been edited it is added to the `Assigned to Others` section which is a bit strange because

1. It was edited by the same person who submitted it
2. Replying to a comment on the `All Comments` page does not automatically assign it to you

**Comment by d4mation** [comment]
Woah, that's weird. I'll have to figure out what is causing that. It should not be Assigning a Comment unless you explicitly tell it to.

> Replying to a comment on the All Comments page does not automatically assign it to you

This second bit has been handled as part of #3
