### ISSUE TITLE
Double gravatar on post page

### ISSUE THREAD

**Issue by jrosebr1** [Py-Image/comment-assignment#4]
In the WP backend I was visiting a blog post to apply some edits. After I applied the edits I scrolled down to reply to a few comments. I then noticed that the gravatar was being displayed twice which seemed a bit odd.

![screen shot 2017-12-13 at 1 41 10 pm](https://user-images.githubusercontent.com/759645/33956060-772b2888-e00b-11e7-83ed-b0e4732d5524.png)

**Comment by jrosebr1** [comment]
I'll also add that once I replied the comment was not assigned to me.

**Comment by d4mation** [comment]
Ah, good catch. I didn't think to check there for that. It is a weird quirk with how WP handles the Comments Table.

Did you reply to the Comment from the Comments Page, or from the Post Edit Screen? I had tested it on the Comments Page(s) and it worked from there. I did not think to check the Post Edit Screen.

**Comment by jrosebr1** [comment]
For this particular example I replied from the Post Edit Scene (not the "All Comments" page).

**Comment by d4mation** [comment]
I just got it working from the Post Edit Screen.

Unfortunately due to limitations in WP Core I cannot add the Assign To/Reply As fields to the Post Edit Screen, but I was able to get Auto-Assigning on Reply working.

I'll get this packaged up as another test build for you :+1:

**Comment by jrosebr1** [comment]
Sounds good. I rarely reply to comments via the Post Edit Screen so it's
not a big deal.
