### ISSUE TITLE
3 Messages Properly Tagged, But Alerted Adrian

### ISSUE THREAD

**Issue by BigActual** [Py-Image/comment-assignment#5]
This came from Adrian last Sunday. Though it is on the docket, it did not get entered as an issue. For tracking purposes, I'm adding it in. 
Adrian [6:02]
Hi Steve -- sorry to ping you on a Sunday but I'm planning on taking a few days off at the end of the week so I'm getting a jump on things.

Eric updated the plugin so that it properly sends email notifications; however, there is still a problem. I woke up this morning and found three email notifications for people who are properly tagged in Drip but the plugin alerted me for:

adrian [6:03 AM]
uploaded this image: Screen Shot 2018-04-15 at 5.16.13 AM.png

adrian [6:03 AM]
This has been happening for the past few weeks.
The plugin needs a round of heavy debugging. I'm happy to pay for it of course, but it needs actually updating and testing. Let me know if you can schedule any time for this, and if so, when.

big_actual [1:43 PM]
shared adrian’s image: Screen Shot 2018-04-15 at 5.16.13 AM.png

**Comment by jrosebr1** [comment]
Hey @BigActual -- this ticket should actually be for the address collection plugin:

https://github.com/Py-Image/PL_PYIS_ADDRESS_COLLECTION

Additionally, I have a second physical book that I am shipping out. I need this plugin to work with another CognitoForms URL and another tag.

The bug label from Steve's initial ticket is correct but additional functionality needs to be added as well.

**Comment by BigActual** [comment]
Moved.

**Comment by d4mation** [comment]
This issue was moved to Py-Image/PL_PYIS_ADDRESS_COLLECTION#10
